# Generated by Django 4.1.2 on 2022-10-15 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Цена (рубли)')),
                ('description', models.CharField(max_length=512, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Цена (рубли)')),
                ('description', models.CharField(max_length=512, verbose_name='Описание')),
                ('number', models.CharField(max_length=5, verbose_name='Номер')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('capacity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=4, verbose_name='Вместимость (человек)')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing.producer', verbose_name='Производитель')),
                ('category', models.ManyToManyField(blank=True, to='sharing.category', verbose_name='Категории')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing.color', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.TextField(verbose_name='Вопрос или проблема')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('tariff', models.IntegerField(choices=[(1, 'Minutes'), (2, 'Hours'), (3, 'Days'), (4, 'Special')], verbose_name='Тариф')),
                ('duration', models.TimeField(blank=True, null=True, verbose_name='Длительность')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('finished', 'Завершенный')], max_length=10, verbose_name='Статус')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing.bike', verbose_name='Велосипед')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Арендатор')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
        migrations.AddField(
            model_name='bike',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing.producer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='bike',
            name='category',
            field=models.ManyToManyField(to='sharing.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='bike',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing.color', verbose_name='Цвет'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('excerpt', models.CharField(max_length=128, verbose_name='Краткое описание')),
                ('preview', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Содержание статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
